import { DOCUMENT } from '@angular/common';
import { Inject, Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export type AppLanguage = 'fr' | 'en' | 'ar';

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly storageKey = 'fraudexia-language';

  private readonly translations: Record<AppLanguage, Record<string, string>> = {
    fr: {
      'app.language': 'Langue',
      'app.language.fr': 'Francais',
      'app.language.en': 'Anglais',
      'app.language.ar': 'Arabe',
      'app.theme': 'Theme',
      'app.theme.light': 'Clair',
      'app.theme.dark': 'Sombre',
      'app.theme.toggleAria': 'Basculer le theme. Mode actuel :',

      'auth.backToSelectionAria': 'Revenir a la selection du role',
      'auth.back': 'Retour',
      'auth.welcomeBack': 'Bienvenue',
      'auth.createYourAccount': 'Creez votre compte',
      'auth.liveDemoMode': 'Mode demo en direct',
      'auth.clientAccount': 'Compte client',
      'auth.adminAccount': 'Compte administrateur',
      'auth.tryNewFlow': 'Essayez le nouveau flux instantanement',
      'auth.launchpadHint': 'Entrez dans les nouveaux tableaux de bord en un clic.',
      'auth.enterAdminMission': 'Entrer dans le centre admin',
      'auth.enterClientHub': 'Entrer dans l\'espace client securite',
      'auth.openAnalystApp': 'Ouvrir l\'app analyst',
      'auth.openApiDocs': 'Ouvrir la doc API',
      'auth.emailOrUsername': 'Email ou nom d\'utilisateur',
      'auth.emailOrUsernamePlaceholder': 'vous@example.com ou identifiant',
      'auth.password': 'Mot de passe',
      'auth.togglePasswordVisibility': 'Afficher ou masquer le mot de passe',
      'auth.toggleConfirmPasswordVisibility': 'Afficher ou masquer la confirmation du mot de passe',
      'auth.login': 'Connexion',
      'auth.clear': 'Effacer',
      'auth.rememberMe': 'Se souvenir de moi',
      'auth.forgotPassword': 'Mot de passe oublie ?',
      'auth.fullName': 'Nom complet',
      'auth.fullNamePlaceholder': 'Jean Dupont',
      'auth.emailAddress': 'Adresse email',
      'auth.emailPlaceholder': 'vous@example.com',
      'auth.passwordHint': 'Min 8 caracteres, 1 majuscule, 1 minuscule, 1 chiffre',
      'auth.confirmPassword': 'Confirmer le mot de passe',
      'auth.agreeTerms': 'J\'accepte les termes et conditions',
      'auth.creatingAccount': 'Creation du compte...',
      'auth.createAccountCta': 'Creer un compte',
      'auth.noAccountQuestion': 'Vous n\'avez pas de compte ?',
      'auth.signUp': 'S\'inscrire',
      'auth.haveAccountQuestion': 'Vous avez deja un compte ?',
      'auth.signIn': 'Se connecter',
      'auth.orContinueWith': 'Ou continuer avec',
      'auth.signInWithGoogle': 'Se connecter avec Google',
      'auth.signInWithGithub': 'Se connecter avec GitHub',
      'auth.signInWithMicrosoft': 'Se connecter avec Microsoft',
      'auth.signInWithApple': 'Se connecter avec Apple',

      'field.identifier': 'Identifiant',
      'field.password': 'Mot de passe',
      'field.fullName': 'Nom complet',
      'field.email': 'Email',
      'field.confirmPassword': 'Confirmation du mot de passe',
      'field.terms': 'Conditions',

      'validation.passwordRequired': 'Le mot de passe est requis',
      'validation.userNotFound': 'Utilisateur introuvable',
      'validation.invalidPassword': 'Mot de passe invalide',
      'validation.invalidEmailOrPassword': 'Email ou mot de passe invalide',
      'validation.authServerError': 'Erreur serveur d\'authentification. Reessayez plus tard.',
      'validation.required': '{field} est requis',
      'validation.invalidEmail': 'Veuillez entrer un email valide',
      'validation.minlength': '{field} doit contenir au moins {min} caracteres',
      'validation.passwordPattern': 'Le mot de passe doit contenir des majuscules, minuscules et chiffres',
      'validation.passwordMismatch': 'Les mots de passe ne correspondent pas',
      'validation.passwordMinLength': 'Le mot de passe doit contenir au moins 8 caracteres',
      'validation.passwordPatternShort': 'Incluez des majuscules, minuscules et chiffres',

      'shell.dashboard': 'Tableau de bord',
      'shell.accounts': 'Comptes',
      'shell.cards': 'Cartes',
      'shell.checks': 'Cheques',
      'shell.topup': 'Recharge telephonique',
      'shell.requests': 'Demandes',
      'shell.converter': 'Convertisseur',
      'shell.simulator': 'Simulateur',
      'shell.branches': 'Agences',
      'shell.logout': 'Deconnexion',

      'admin.centerTitle': 'Centre Fraude RCC Bank',
      'admin.searchPlaceholder': 'Rechercher alertes, utilisateurs ou transactions...',
      'admin.activeAlerts': 'Alertes actives',
      'admin.forensicConsole': 'Console Forensique',
      'admin.aiLab': 'Laboratoire IA',
      'admin.openCases': 'Cas ouverts',
      'admin.escalated': 'Escalades',
      'admin.investigating': 'En investigation',
      'admin.aiThreshold': 'Seuil IA',
      'admin.alerts': 'Alertes',
      'admin.falsePositives': 'Faux positifs',
      'admin.precision': 'Precision',
      'admin.meanRisk': 'Risque moyen',
      'admin.thisWeek': 'cette semaine',
      'admin.improvement': 'amelioration',
      'admin.lastMonth': 'mois dernier',
      'admin.currentLevel': 'niveau actuel',
      'admin.monitor': 'Surveiller',
      'admin.good': 'Bon',
      'admin.hotspots': 'Zones fraude - Vue globale',
      'admin.modelPerformance': 'Performance des modeles IA',
      'admin.liveFeed': 'Flux d\'alertes en direct',
      'admin.active': 'Actives',
      'admin.client': 'CLIENT',
      'admin.user': 'Utilisateur',
      'admin.risk': 'Risque',
      'admin.deepDive': 'Analyse detaillee',
      'admin.workflow': 'Tableau de workflow d\'investigation',
      'admin.totalCases': 'cas au total',
      'admin.triage': 'TRIAGE',
      'admin.investigatingUpper': 'INVESTIGATION',
      'admin.escalatedUpper': 'ESCALADE',
      'admin.sla': 'SLA',
      'admin.assignAnalyst': 'Assigner analyste',
      'admin.assign': 'Assigner',
      'admin.start': 'Demarrer',
      'admin.unassigned': 'Non assigne',
      'admin.seniorQueue': 'File senior',
      'admin.escalate': 'Escalader',
      'admin.confirmFraud': 'Confirmer fraude',
      'admin.review': 'Revoir',
      'admin.backToLogin': 'Retour connexion',

      'client.securitySubtitle': 'Securisez vos transactions avec la protection anti-fraude en temps reel',
      'client.activeAlertsTitle': 'alertes actives',
      'client.openCases': 'cas ouvert(s)',
      'client.mainCard': 'Carte principale',
      'client.holder': 'TITULAIRE',
      'client.expires': 'EXPIRE',
      'client.currentBalance': 'Solde actuel',
      'client.creditLimit': 'Limite de credit',
      'client.unfreeze': 'Debloquer carte',
      'client.freeze': 'Bloquer carte',
      'client.cardFrozen': 'Statut carte: Bloquee',
      'client.cardActive': 'Statut carte: Active',
      'client.trustScore': 'Score de confiance',
      'client.secure': 'Securise',
      'client.moderate': 'Modere',
      'client.risky': 'Risque',
      'client.securityAssessment': 'Evaluation de securite',
      'client.realtimeMonitoring': 'Surveillance en temps reel active',
      'client.locationModel': 'Modele de localisation verifie',
      'client.waitingReview': 'transactions en attente d\'examen',
      'client.noSuspicious': 'Aucune activite suspecte detectee',
      'client.recentTransactions': 'Transactions recentes',
      'client.blockedByPolicy': 'Bloquee par la politique carte',
      'client.reportFraud': 'Signaler comme fraude',
      'client.awaitingReview': 'En attente d\'examen',
      'client.wasMe': 'Oui, c\'etait moi',
      'client.notMe': 'Non, ce n\'etait pas moi',
      'client.verified': 'Verifiee',
      'client.trustMerchant': 'Faire confiance',
      'client.trusted': 'Fiable',
      'client.underInvestigation': 'En investigation',
      'client.caseOpened': 'CAS OUVERT',
      'client.noTransactions': 'Aucune transaction trouvee',
      'client.merchantVault': 'Coffre des marchands fiables',
      'client.trustedList': 'Liste fiable',
      'client.remove': 'Retirer',
      'client.recommended': 'Recommandes a approuver',
      'client.noTrustedYet': 'Aucun marchand fiable',
      'client.noSuggestions': 'Aucune suggestion',
      'client.travelMode': 'Mode voyage',
      'client.travelSubtitle': 'Acceptez les pays pour les transactions en voyage',
      'client.approvedPlaces': 'Lieux approuves',
      'client.addDestination': 'Ajouter une destination',
      'client.allCountriesAdded': 'Tous les pays ajoutes',
      'client.fraudSubmitted': 'Rapport de fraude soumis',
      'client.reportFailed': 'Echec du rapport',
      'client.myRecentCases': 'Mes cas fraude recents',
      'client.priority': 'Priorite',
      'client.by': 'Par'
    },
    en: {
      'app.language': 'Language',
      'app.language.fr': 'French',
      'app.language.en': 'English',
      'app.language.ar': 'Arabic',
      'app.theme': 'Theme',
      'app.theme.light': 'Light',
      'app.theme.dark': 'Dark',
      'app.theme.toggleAria': 'Toggle theme. Current mode:',

      'auth.backToSelectionAria': 'Go back to role selection',
      'auth.back': 'Back',
      'auth.welcomeBack': 'Welcome back',
      'auth.createYourAccount': 'Create your account',
      'auth.liveDemoMode': 'Live Demo Mode',
      'auth.clientAccount': 'Client Account',
      'auth.adminAccount': 'Administrator Account',
      'auth.tryNewFlow': 'Try The New Flow Instantly',
      'auth.launchpadHint': 'Use one click to enter the upgraded dashboards.',
      'auth.enterAdminMission': 'Enter Admin Mission Control',
      'auth.enterClientHub': 'Enter Client Security Hub',
      'auth.openAnalystApp': 'Open Analyst App',
      'auth.openApiDocs': 'Open API Docs',
      'auth.emailOrUsername': 'Email or Username',
      'auth.emailOrUsernamePlaceholder': 'you@example.com or username',
      'auth.password': 'Password',
      'auth.togglePasswordVisibility': 'Toggle password visibility',
      'auth.toggleConfirmPasswordVisibility': 'Toggle confirm password visibility',
      'auth.login': 'Login',
      'auth.clear': 'Clear',
      'auth.rememberMe': 'Remember me',
      'auth.forgotPassword': 'Forgot password?',
      'auth.fullName': 'Full Name',
      'auth.fullNamePlaceholder': 'John Doe',
      'auth.emailAddress': 'Email Address',
      'auth.emailPlaceholder': 'you@example.com',
      'auth.passwordHint': 'Min 8 chars, 1 uppercase, 1 lowercase, 1 number',
      'auth.confirmPassword': 'Confirm Password',
      'auth.agreeTerms': 'I agree to the Terms and Conditions',
      'auth.creatingAccount': 'Creating account...',
      'auth.createAccountCta': 'Create account',
      'auth.noAccountQuestion': "Don't have an account?",
      'auth.signUp': 'Sign up',
      'auth.haveAccountQuestion': 'Already have an account?',
      'auth.signIn': 'Sign in',
      'auth.orContinueWith': 'Or continue with',
      'auth.signInWithGoogle': 'Sign in with Google',
      'auth.signInWithGithub': 'Sign in with GitHub',
      'auth.signInWithMicrosoft': 'Sign in with Microsoft',
      'auth.signInWithApple': 'Sign in with Apple',

      'field.identifier': 'Identifier',
      'field.password': 'Password',
      'field.fullName': 'Full Name',
      'field.email': 'Email',
      'field.confirmPassword': 'Confirm Password',
      'field.terms': 'Terms',

      'validation.passwordRequired': 'Password is required',
      'validation.userNotFound': 'User not found',
      'validation.invalidPassword': 'Invalid password',
      'validation.invalidEmailOrPassword': 'Invalid email or password',
      'validation.authServerError': 'Authentication server error. Please try again later.',
      'validation.required': '{field} is required',
      'validation.invalidEmail': 'Please enter a valid email address',
      'validation.minlength': '{field} must be at least {min} characters',
      'validation.passwordPattern': 'Password must contain uppercase, lowercase, and numbers',
      'validation.passwordMismatch': 'Passwords do not match',
      'validation.passwordMinLength': 'Password must be at least 8 characters',
      'validation.passwordPatternShort': 'Include uppercase, lowercase, and numbers',

      'shell.dashboard': 'Dashboard',
      'shell.accounts': 'Accounts',
      'shell.cards': 'Cards',
      'shell.checks': 'Checks',
      'shell.topup': 'Mobile Top-up',
      'shell.requests': 'Requests',
      'shell.converter': 'Converter',
      'shell.simulator': 'Simulator',
      'shell.branches': 'Branches',
      'shell.logout': 'Logout',

      'admin.centerTitle': 'RCC Bank Fraud Center',
      'admin.searchPlaceholder': 'Search alerts, users, or transactions...',
      'admin.activeAlerts': 'Active Alerts',
      'admin.forensicConsole': 'Forensic Console',
      'admin.aiLab': 'AI Laboratory',
      'admin.openCases': 'Open Cases',
      'admin.escalated': 'Escalated',
      'admin.investigating': 'Investigating',
      'admin.aiThreshold': 'AI Threshold',
      'admin.alerts': 'Alerts',
      'admin.falsePositives': 'False Positives',
      'admin.precision': 'Precision',
      'admin.meanRisk': 'Mean Risk Score',
      'admin.thisWeek': 'this week',
      'admin.improvement': 'improvement',
      'admin.lastMonth': 'last month',
      'admin.currentLevel': 'current level',
      'admin.monitor': 'Monitor',
      'admin.good': 'Good',
      'admin.hotspots': 'Fraud Hotspots - Global View',
      'admin.modelPerformance': 'AI Model Performance',
      'admin.liveFeed': 'Live Alert Feed',
      'admin.active': 'Active',
      'admin.client': 'CLIENT',
      'admin.user': 'User',
      'admin.risk': 'Risk',
      'admin.deepDive': 'Deep Dive',
      'admin.workflow': 'Investigation Workflow Board',
      'admin.totalCases': 'total case(s)',
      'admin.triage': 'TRIAGE',
      'admin.investigatingUpper': 'INVESTIGATING',
      'admin.escalatedUpper': 'ESCALATED',
      'admin.sla': 'SLA',
      'admin.assignAnalyst': 'Assign analyst',
      'admin.assign': 'Assign',
      'admin.start': 'Start',
      'admin.unassigned': 'Unassigned',
      'admin.seniorQueue': 'Senior Queue',
      'admin.escalate': 'Escalate',
      'admin.confirmFraud': 'Confirm Fraud',
      'admin.review': 'Review',
      'admin.backToLogin': 'Back to Login',

      'client.securitySubtitle': 'Secure your transactions with real-time fraud protection',
      'client.activeAlertsTitle': 'active alerts',
      'client.openCases': 'case(s) open',
      'client.mainCard': 'Main Card',
      'client.holder': 'HOLDER',
      'client.expires': 'EXPIRES',
      'client.currentBalance': 'Current Balance',
      'client.creditLimit': 'Credit Limit',
      'client.unfreeze': 'Unfreeze Card',
      'client.freeze': 'Freeze Card',
      'client.cardFrozen': 'Card Status: Frozen',
      'client.cardActive': 'Card Status: Active',
      'client.trustScore': 'Trust Score',
      'client.secure': 'Secure',
      'client.moderate': 'Moderate',
      'client.risky': 'Risky',
      'client.securityAssessment': 'Security Assessment',
      'client.realtimeMonitoring': 'Real-time monitoring active',
      'client.locationModel': 'Location model verified',
      'client.waitingReview': 'transactions waiting review',
      'client.noSuspicious': 'No suspicious activity detected',
      'client.recentTransactions': 'Recent Transactions',
      'client.blockedByPolicy': 'Blocked By Card Security Policy',
      'client.reportFraud': 'Report As Fraud',
      'client.awaitingReview': 'Awaiting Review',
      'client.wasMe': 'Yes, it was me',
      'client.notMe': 'No, it was not me',
      'client.verified': 'Verified',
      'client.trustMerchant': 'Trust Merchant',
      'client.trusted': 'Trusted',
      'client.underInvestigation': 'Under Investigation',
      'client.caseOpened': 'CASE OPENED',
      'client.noTransactions': 'No transactions found',
      'client.merchantVault': 'Trusted Merchant Vault',
      'client.trustedList': 'Trusted List',
      'client.remove': 'Remove',
      'client.recommended': 'Recommended To Trust',
      'client.noTrustedYet': 'No trusted merchants yet',
      'client.noSuggestions': 'No new suggestions',
      'client.travelMode': 'Travel Mode',
      'client.travelSubtitle': 'Allow countries for seamless travel transactions',
      'client.approvedPlaces': 'Approved Places',
      'client.addDestination': 'Add Destination',
      'client.allCountriesAdded': 'All countries added',
      'client.fraudSubmitted': 'Fraud Report Submitted',
      'client.reportFailed': 'Report Failed',
      'client.myRecentCases': 'My Recent Fraud Cases',
      'client.priority': 'Priority',
      'client.by': 'By'
    },
    ar: {
      'app.language': 'اللغة',
      'app.language.fr': 'الفرنسية',
      'app.language.en': 'الانجليزية',
      'app.language.ar': 'العربية',
      'app.theme': 'السمة',
      'app.theme.light': 'فاتح',
      'app.theme.dark': 'داكن',
      'app.theme.toggleAria': 'تبديل السمة. الوضع الحالي:',

      'auth.backToSelectionAria': 'العودة الى اختيار الدور',
      'auth.back': 'رجوع',
      'auth.welcomeBack': 'مرحبا بعودتك',
      'auth.createYourAccount': 'انشئ حسابك',
      'auth.liveDemoMode': 'وضع العرض المباشر',
      'auth.clientAccount': 'حساب العميل',
      'auth.adminAccount': 'حساب المسؤول',
      'auth.tryNewFlow': 'جرب التدفق الجديد فورا',
      'auth.launchpadHint': 'ادخل الى لوحات التحكم المطورة بنقرة واحدة.',
      'auth.enterAdminMission': 'الدخول الى مركز ادارة النظام',
      'auth.enterClientHub': 'الدخول الى مركز امن العميل',
      'auth.openAnalystApp': 'فتح تطبيق المحلل',
      'auth.openApiDocs': 'فتح توثيق API',
      'auth.emailOrUsername': 'البريد الالكتروني او اسم المستخدم',
      'auth.emailOrUsernamePlaceholder': 'you@example.com او اسم المستخدم',
      'auth.password': 'كلمة المرور',
      'auth.togglePasswordVisibility': 'اظهار او اخفاء كلمة المرور',
      'auth.toggleConfirmPasswordVisibility': 'اظهار او اخفاء تاكيد كلمة المرور',
      'auth.login': 'تسجيل الدخول',
      'auth.clear': 'مسح',
      'auth.rememberMe': 'تذكرني',
      'auth.forgotPassword': 'هل نسيت كلمة المرور؟',
      'auth.fullName': 'الاسم الكامل',
      'auth.fullNamePlaceholder': 'الاسم الكامل',
      'auth.emailAddress': 'عنوان البريد الالكتروني',
      'auth.emailPlaceholder': 'you@example.com',
      'auth.passwordHint': '8 احرف على الاقل، حرف كبير، حرف صغير، ورقم',
      'auth.confirmPassword': 'تاكيد كلمة المرور',
      'auth.agreeTerms': 'اوافق على الشروط والاحكام',
      'auth.creatingAccount': 'جاري انشاء الحساب...',
      'auth.createAccountCta': 'انشاء حساب',
      'auth.noAccountQuestion': 'ليس لديك حساب؟',
      'auth.signUp': 'انشاء حساب',
      'auth.haveAccountQuestion': 'لديك حساب بالفعل؟',
      'auth.signIn': 'تسجيل الدخول',
      'auth.orContinueWith': 'او المتابعة باستخدام',
      'auth.signInWithGoogle': 'تسجيل الدخول عبر Google',
      'auth.signInWithGithub': 'تسجيل الدخول عبر GitHub',
      'auth.signInWithMicrosoft': 'تسجيل الدخول عبر Microsoft',
      'auth.signInWithApple': 'تسجيل الدخول عبر Apple',

      'field.identifier': 'المعرف',
      'field.password': 'كلمة المرور',
      'field.fullName': 'الاسم الكامل',
      'field.email': 'البريد الالكتروني',
      'field.confirmPassword': 'تاكيد كلمة المرور',
      'field.terms': 'الشروط',

      'validation.passwordRequired': 'كلمة المرور مطلوبة',
      'validation.userNotFound': 'المستخدم غير موجود',
      'validation.invalidPassword': 'كلمة المرور غير صحيحة',
      'validation.invalidEmailOrPassword': 'البريد الالكتروني او كلمة المرور غير صحيحة',
      'validation.authServerError': 'خطا في خادم المصادقة. حاول مرة اخرى لاحقا.',
      'validation.required': '{field} مطلوب',
      'validation.invalidEmail': 'يرجى ادخال بريد الكتروني صحيح',
      'validation.minlength': '{field} يجب ان يحتوي على {min} احرف على الاقل',
      'validation.passwordPattern': 'يجب ان تحتوي كلمة المرور على حروف كبيرة وصغيرة وارقام',
      'validation.passwordMismatch': 'كلمتا المرور غير متطابقتين',
      'validation.passwordMinLength': 'كلمة المرور يجب ان تكون 8 احرف على الاقل',
      'validation.passwordPatternShort': 'استخدم حروف كبيرة وصغيرة وارقاما',

      'shell.dashboard': 'لوحة التحكم',
      'shell.accounts': 'الحسابات',
      'shell.cards': 'البطاقات',
      'shell.checks': 'الشيكات',
      'shell.topup': 'شحن الهاتف',
      'shell.requests': 'الطلبات',
      'shell.converter': 'محول العملات',
      'shell.simulator': 'المحاكي',
      'shell.branches': 'الوكالات',
      'shell.logout': 'تسجيل الخروج',

      'admin.centerTitle': 'مركز احتيال البنك',
      'admin.searchPlaceholder': 'ابحث عن التنبيهات او المستخدمين او المعاملات...',
      'admin.activeAlerts': 'تنبيهات نشطة',
      'admin.forensicConsole': 'لوحة التحليل الجنائي',
      'admin.aiLab': 'مختبر الذكاء الاصطناعي',
      'admin.openCases': 'حالات مفتوحة',
      'admin.escalated': 'مصعدة',
      'admin.investigating': 'قيد التحقيق',
      'admin.aiThreshold': 'عتبة الذكاء الاصطناعي',
      'admin.alerts': 'تنبيهات',
      'admin.falsePositives': 'ايجابيات كاذبة',
      'admin.precision': 'الدقة',
      'admin.meanRisk': 'متوسط المخاطر',
      'admin.thisWeek': 'هذا الاسبوع',
      'admin.improvement': 'تحسن',
      'admin.lastMonth': 'الشهر الماضي',
      'admin.currentLevel': 'المستوى الحالي',
      'admin.monitor': 'مراقبة',
      'admin.good': 'جيد',
      'admin.hotspots': 'بؤر الاحتيال - عرض عالمي',
      'admin.modelPerformance': 'اداء نماذج الذكاء الاصطناعي',
      'admin.liveFeed': 'بث التنبيهات المباشر',
      'admin.active': 'نشط',
      'admin.client': 'العميل',
      'admin.user': 'المستخدم',
      'admin.risk': 'المخاطر',
      'admin.deepDive': 'تحليل معمق',
      'admin.workflow': 'لوحة سير التحقيق',
      'admin.totalCases': 'اجمالي الحالات',
      'admin.triage': 'فرز',
      'admin.investigatingUpper': 'تحقيق',
      'admin.escalatedUpper': 'تصعيد',
      'admin.sla': 'مستوى الخدمة',
      'admin.assignAnalyst': 'تعيين محلل',
      'admin.assign': 'تعيين',
      'admin.start': 'ابدأ',
      'admin.unassigned': 'غير معين',
      'admin.seniorQueue': 'قائمة الخبراء',
      'admin.escalate': 'تصعيد',
      'admin.confirmFraud': 'تأكيد الاحتيال',
      'admin.review': 'مراجعة',
      'admin.backToLogin': 'العودة لتسجيل الدخول',

      'client.securitySubtitle': 'امّن معاملاتك مع حماية فورية ضد الاحتيال',
      'client.activeAlertsTitle': 'تنبيهات نشطة',
      'client.openCases': 'حالة مفتوحة',
      'client.mainCard': 'البطاقة الرئيسية',
      'client.holder': 'صاحب البطاقة',
      'client.expires': 'تنتهي',
      'client.currentBalance': 'الرصيد الحالي',
      'client.creditLimit': 'حد الائتمان',
      'client.unfreeze': 'الغاء تجميد البطاقة',
      'client.freeze': 'تجميد البطاقة',
      'client.cardFrozen': 'حالة البطاقة: مجمدة',
      'client.cardActive': 'حالة البطاقة: نشطة',
      'client.trustScore': 'درجة الثقة',
      'client.secure': 'آمن',
      'client.moderate': 'متوسط',
      'client.risky': 'خطر',
      'client.securityAssessment': 'تقييم الامان',
      'client.realtimeMonitoring': 'مراقبة فورية مفعلة',
      'client.locationModel': 'نموذج الموقع موثّق',
      'client.waitingReview': 'معاملة بانتظار المراجعة',
      'client.noSuspicious': 'لا توجد نشاطات مشبوهة',
      'client.recentTransactions': 'المعاملات الحديثة',
      'client.blockedByPolicy': 'محجوبة بسبب سياسة البطاقة',
      'client.reportFraud': 'ابلاغ عن احتيال',
      'client.awaitingReview': 'بانتظار المراجعة',
      'client.wasMe': 'نعم انا قمت بها',
      'client.notMe': 'لا لم اقم بها',
      'client.verified': 'تم التحقق',
      'client.trustMerchant': 'تاجر موثوق',
      'client.trusted': 'موثوق',
      'client.underInvestigation': 'قيد التحقيق',
      'client.caseOpened': 'تم فتح الحالة',
      'client.noTransactions': 'لا توجد معاملات',
      'client.merchantVault': 'خزنة التجار الموثوقين',
      'client.trustedList': 'القائمة الموثوقة',
      'client.remove': 'حذف',
      'client.recommended': 'مقترح للثقة',
      'client.noTrustedYet': 'لا يوجد تجار موثوقون',
      'client.noSuggestions': 'لا توجد اقتراحات',
      'client.travelMode': 'وضع السفر',
      'client.travelSubtitle': 'اسمح بالدول للمعاملات اثناء السفر',
      'client.approvedPlaces': 'اماكن معتمدة',
      'client.addDestination': 'اضافة وجهة',
      'client.allCountriesAdded': 'تمت اضافة كل الدول',
      'client.fraudSubmitted': 'تم ارسال بلاغ الاحتيال',
      'client.reportFailed': 'فشل البلاغ',
      'client.myRecentCases': 'احدث حالات الاحتيال',
      'client.priority': 'الاولوية',
      'client.by': 'بواسطة'
    }
  };

  private readonly currentLanguageSubject = new BehaviorSubject<AppLanguage>('fr');
  readonly currentLanguage$ = this.currentLanguageSubject.asObservable();

  constructor(@Inject(DOCUMENT) private readonly document: Document) {}

  init(): AppLanguage {
    const stored = this.readStoredLanguage();
    this.currentLanguageSubject.next(stored);
    this.applyLanguage(stored);
    return stored;
  }

  setLanguage(language: AppLanguage): void {
    this.currentLanguageSubject.next(language);
    this.persistLanguage(language);
    this.applyLanguage(language);
  }

  getCurrentLanguage(): AppLanguage {
    return this.currentLanguageSubject.value;
  }

  translate(key: string): string {
    const lang = this.currentLanguageSubject.value;
    return this.translations[lang][key] ?? this.translations.en[key] ?? key;
  }

  private readStoredLanguage(): AppLanguage {
    if (typeof window === 'undefined') {
      return 'fr';
    }

    const raw = window.localStorage.getItem(this.storageKey);
    if (raw === 'fr' || raw === 'en' || raw === 'ar') {
      return raw;
    }

    return 'fr';
  }

  private persistLanguage(language: AppLanguage): void {
    if (typeof window === 'undefined') {
      return;
    }

    window.localStorage.setItem(this.storageKey, language);
  }

  private applyLanguage(language: AppLanguage): void {
    const root = this.document.documentElement;
    root.setAttribute('lang', language);

    const isRtl = language === 'ar';
    root.setAttribute('dir', isRtl ? 'rtl' : 'ltr');
    this.document.body.setAttribute('dir', isRtl ? 'rtl' : 'ltr');
  }
}
